version : "3.8"

services:
  django:
    build: 
      context: ./weatherforecast
    image: ngovanlau/weather-forecast-api
    restart: always
    environment:
      WEATHER_API_KEY: 6b86ead5872c405488a162337242309
      REDIS_HOST: redis-15593.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com
      REDIS_PORT: 15593
      REDIS_PASSWORD: Ao9Fky1wJBslnvgaELL0t7h4WPoopFHM
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "8000:8000"
    networks:
      - app-network

  reactjs:
    build:
      context: ./weather-forecast-web
    restart: always
    image: ngovanlau/weather-forecast-web
    environment: 
      REACT_APP_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - django
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: {}